name: tienda_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  google_sign_in: ^6.2.2
  lottie: ^3.1.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/email_icon.png
    - assets/nike_shoe.png
    - assets/error_animation.json
    - assets/imagen_no_disponible.png