// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_JU16H4eOcaQQUlGQ1JyC3n2oD6jaDao',
    appId: '1:419483250156:web:4ef44d91a5e34ca635e4c9',
    messagingSenderId: '419483250156',
    projectId: 'tiendabloc-532e1',
    authDomain: 'tiendabloc-532e1.firebaseapp.com',
    storageBucket: 'tiendabloc-532e1.firebasestorage.app',
    measurementId: 'G-G0V0GXZBCZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSpLcEBG_4yAae66FLzpKhOFYPqUGitF4',
    appId: '1:419483250156:ios:19d097a83614eac735e4c9',
    messagingSenderId: '419483250156',
    projectId: 'tiendabloc-532e1',
    storageBucket: 'tiendabloc-532e1.firebasestorage.app',
    iosBundleId: 'com.example.tiendaBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSpLcEBG_4yAae66FLzpKhOFYPqUGitF4',
    appId: '1:419483250156:ios:19d097a83614eac735e4c9',
    messagingSenderId: '419483250156',
    projectId: 'tiendabloc-532e1',
    storageBucket: 'tiendabloc-532e1.firebasestorage.app',
    iosBundleId: 'com.example.tiendaBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_JU16H4eOcaQQUlGQ1JyC3n2oD6jaDao',
    appId: '1:419483250156:web:9c9560390018198e35e4c9',
    messagingSenderId: '419483250156',
    projectId: 'tiendabloc-532e1',
    authDomain: 'tiendabloc-532e1.firebaseapp.com',
    storageBucket: 'tiendabloc-532e1.firebasestorage.app',
    measurementId: 'G-RQ186XKWYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYFT8m-WmJR2IZsPmU793JfK3UnF4e85M',
    appId: '1:419483250156:android:4e793387bef3eb4435e4c9',
    messagingSenderId: '419483250156',
    projectId: 'tiendabloc-532e1',
    storageBucket: 'tiendabloc-532e1.firebasestorage.app',
  );

}